spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin123456
    url: jdbc:mysql://192.168.1.200/babytun?characterEncoding=UTF-8
mybatis:
  mapper-locations: classpath://sqlmap/*.xml
